<a href="https://colab.research.google.com/github/akshaypatwari47/ML/blob/master/day_9(03_06_20).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
#password picker assignment of 01.06.20
import string
from random import *#random should be written while using choice function          or import random can be used    
print("Welcome to password picker!!!")
adj = ["excellent","verygood","good","bad","poor"]
noun = ["santu","supriya","saas","santhoshi","sai"]
digits = string.digits
spl_char = string.punctuation

Welcome to password picker!!!


In [0]:
while True:
  password = choice(adj) + choice(noun) + choice(digits) + choice(spl_char)
  print("your password is :" ,password)
  print("do you want to generate another password?")
  response = input("enter yes for new password no for not generating the password!!")
  if response in ["no","No","NO","nO"] :
    break
  elif response in ["yes","Yes"]:
    continue
  else:
    print("enter either yes or no!!!")

your password is : poorsaas2.
do you want to generate another password?
enter yes for new password no for not generating the password!!yes
your password is : goodsantu3[
do you want to generate another password?
enter yes for new password no for not generating the password!!akshay@9000
enter either yes or no!!!
your password is : goodsanthoshi8=
do you want to generate another password?
enter yes for new password no for not generating the password!!no


In [0]:
##Module:
1.pre-defined modules
2.User- defined modules

In [0]:
import string
string.digits

'0123456789'

In [0]:
import string as s#as repersents alias name for string
s.digits

'0123456789'

In [0]:
from string import digits,punctuation
print(digits)
print(punctuation)

0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [0]:
from string import *#  * is to import all the types of methods
print(digits)
print(punctuation)

0123456789
!"#$%&'()*+,-./:;<=>?@[\]^_`{|}~


In [0]:
list1 = [1,2,3,4,5]
su = 0#integer
for i in list1:
  su += i
print(su) 

15


In [0]:
sum(list1)

In [0]:
#user defined modules:i.e creting our own modules
go to folderin which jupyter is present
click on new and then text file
a untitled text file is opened
click on lang and select it as python
rename your text file to operations.python
more two steps are present ...check it
add your code nown (used functions)
save it and close the file

In [0]:
import operations
operations.wish("akshay")#we get output according to the code we have written

In [0]:
import operations as o
o.wish("patwari")
o.result#can use help("operations") to get your code in operations file

In [0]:
#builtin libraries:
1.math
2.statistics

In [0]:
import math

In [0]:
help("math")

In [0]:
import math
math.factorial(6)

720

In [0]:
#radius#using math module find area of the circle
def Area(radius):
 return math.pi*(radius)*radius


Area(6)

113.09733552923255

In [0]:
import statistics as s
list1 = list(range(1,21))
list1

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

In [0]:
print(s.mean(list1))#gives mean value of all elements
print(sum(list1)/len(list1))#error is due to sum used before try it alone

In [0]:
list2= [1,2,3,2,3,2]
print(s.mode(list2))

2


In [0]:
print(s.median(list1))

10.5


In [0]:
s.stdev(list2)#standard deviation


0.752772652709081

In [0]:
s.variance(list2)#variance

0.5666666666666667

In [0]:
##random:it is a builtin methods
1.randit() -->randit(start,stop)
2.random()
3.choice()
4.randrange()

In [0]:
import random
print(random.randint(1,10))#start and stop values are included ,a random number is printed
print(random.randrange(1,10))#stop value is excluded                    random and randrange are to generate random integers
print(random.random())#creates random float value between 0 and 1

8
9
0.3231924059761333


In [0]:
list1 = [1,2,3,4,5,6,7,8]
print(random.choice(list1))#choice generates element from the given list
print(random.choices(list1,k = 5))#k represents number of are to be extracted from list          choices is to extract multiple elements

8
[6, 1, 3, 7, 4]


In [0]:
#os:
1.rename()-->renaming
2.remove()-->removing
3.mkdir()-->make a directory
4.getcwd()-->gives current working directory
5.listdir()-->gives list of things available in directory
6.chdir()-->change directory
7.rmdir()-->removing directory

In [0]:
import os
os.mkdir("sample")

In [0]:
os.getcwd()#pwd is present only in jupyter so cwd can be used anywhere

In [0]:
os.listdir()

In [0]:
os.chdir(......................\\otherfoldername)

In [0]:
#while removing a folder make sure that that folder is empty
os.rmdir("sample")

In [0]:
##Numpy packages:
-operations related to numerics
-computational operations

In [0]:
import numpy as np
list1 = [1,2,3,4,5]
arr1 = np.array(list1)#creating an array
arr1

array([1, 2, 3, 4, 5])

In [0]:
type(arr1)

numpy.ndarray

In [0]:
list2 = list(range(1,11))
list2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [0]:
arr2 = np.arange(1,11)#other way of creating an array in numpy
arr2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [0]:
##differences between python list and numpy array
-Numpy uses less memory
-numpy is fast
-numpy arrays are most convinient

In [0]:
import sys#sys is module which contains function get sizeof
size = 1000
list1 = list(range(size))
print(sys.getsizeof(list1[0]))

24


In [0]:
print(sys.getsizeof(list1[0])*size)

24000


In [0]:
size = 1000#less memory
list1 = list(range(size))
print(sys.getsizeof(list1[0])*size)
arr1 = np.arange(1000)
print(arr1.itemsize * arr1.size)

24000
8000


In [0]:
import time
size = 20000
list1 = list(range(size))
list2 = list(range(size))
start = time.time()
result = [x+y for x,y in zip(l1,l2)]
print("timetaken for list:",time.time()-start)
arr1 = np.arange(size)
arr2 = np.arange(size)
start = time.time()
result = arr1 + arr2
print("timetaken for numpy:",time.time()-start)

NameError: ignored

In [0]:
l1 = [1,2,3,4,5]
l2 = [10,13,15,56,25]
result = [11,15,18,60,30]
result

[11, 15, 18, 60, 30]

In [0]:
a1 = np.array(l1)
a2 = np.array(l2)
result = a1 +a2 
result

array([11, 15, 18, 60, 30])