<a href="https://colab.research.google.com/github/akshaypatwari47/ML/blob/master/day_11(05_06_20).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from numpy import random
print(random.randint(1,100))##random integer in given range
print(random.rand())#float number 0-1

91
0.008822851256799824


In [0]:
print(random.randint(100,size=(3)))#array of size 3    creating n dimensional array with random integer values
print(random.randint(100,size=(3,2)))
print(random.randint(100,size=(3,4,2)))

[63 14 17]
[[93 29]
 [45 58]
 [ 9 70]]
[[[56 11]
  [ 2 78]
  [ 5 62]
  [95 91]]

 [[44 95]
  [37 79]
  [89 87]
  [52 63]]

 [[46 50]
  [48 46]
  [30 57]
  [76 73]]]


In [0]:
#with floating point values
print(random.rand())
print(random.rand(3))
print(random.rand(3,2))

0.7175144031779133
[0.42817165 0.25122447 0.5733634 ]
[[0.10189304 0.16129422]
 [0.83317592 0.10979888]
 [0.91887556 0.67774403]]


In [0]:
a = print(random.randint(100,size=(3,4)))
a

[[66 66 83 87]
 [85 30 37 50]
 [36 50 80 93]]


In [0]:
#to use choice the array should be 1dimensional
a = (random.randint(100,size=(3,4))).ravel()
random.choice(a)#gives a single element

87

In [0]:
#for generating an array with the given shape and elements from the given list
random.choice([1,2,3,4,5],size = (3,4))

array([[2, 1, 3, 3],
       [5, 3, 5, 4],
       [3, 4, 5, 1]])

In [0]:
#Pandas:
-Data manipulation,analysis and cleaning                    are performed using pandas
-Tabular Data,Unlabelled data

SyntaxError: ignored

In [0]:
#Creating a DataFrame
-using two DICTIONARIES
-simple dictionary--->DataFrame

SyntaxError: ignored

In [0]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}#keys reperesent rows and values represent colomn
dict2 = {'a':5,'b':6,'c':7,'d':8,'e':9}
data = {"First":dict1,"Second":dict2}
df = pd.DataFrame(data,dtype= np.int32)
df

First  Second
a      1       5
b      2       6
c      3       7
d      4       8
e      5       9

In [0]:
import pandas as pd
import numpy as np
dict1 = {'a':1,'b':2,'c':3,'d':4,'e':5}#keys reperesent rows and values represent colomn
dict2 = {'a':5,'b':6,'c':7,'d':8,'f':9}
data = {"First":dict1,"Second":dict2}#Nan is not a number
df = pd.DataFrame(data)
df

First  Second
a    1.0     5.0
b    2.0     6.0
c    3.0     7.0
d    4.0     8.0
e    5.0     NaN
f    NaN     9.0

In [0]:
#simple dictionary--->DataFrame
d1 = {"name":["santu","suppi","mouni"],"address":["mach","manch","chittt"]}
df1 = pd.DataFrame(d1)#in this the row indexes are by gefault from 0
df1

name address
0  santu    mach
1  suppi   manch
2  mouni  chittt

In [0]:
#Using series                 series is a part of dataframe
s1 = pd.Series([1,2,3,4,5,6,7,8,9,10])
s2 = pd.Series([12.23,23.34,34.45,45.56,56.67,67.78,78.89,89.90,25.36,69.3])
s3 = pd.Series(['a','b','c','d','e','f','g','h','i','j'])
data = {"column1":s1,"column2":s2,"column3":s3}
df3 = pd.DataFrame(data)
df3

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c
3        4    45.56       d
4        5    56.67       e
5        6    67.78       f
6        7    78.89       g
7        8    89.90       h
8        9    25.36       i
9       10    69.30       j

In [0]:
#Selecting the data from dataframe  : loc,iloc and direct method
df3["column2"]

0    12.23
1    23.34
2    34.45
3    45.56
4    56.67
5    67.78
6    78.89
7    89.90
8    25.36
9    69.30
Name: column2, dtype: float64

In [0]:
df3[["column2","column3"]]

column2 column3
0    12.23       a
1    23.34       b
2    34.45       c
3    45.56       d
4    56.67       e
5    67.78       f
6    78.89       g
7    89.90       h
8    25.36       i
9    69.30       j

In [0]:
df3.loc[:,"column1"]#indicates rows and columns

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [0]:
df3.loc[:,["column1","column2","column3"]]#start to end values are inserted

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c
3        4    45.56       d
4        5    56.67       e
5        6    67.78       f
6        7    78.89       g
7        8    89.90       h
8        9    25.36       i
9       10    69.30       j

In [0]:
df3.loc[0:5,["column1","column2","column3"]]#DataFrame.loc[rows,columns]

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c
3        4    45.56       d
4        5    56.67       e
5        6    67.78       f

In [0]:
type(df3)

pandas.core.frame.DataFrame

In [0]:
df3.iloc[:,0]#i stamds for index

0     1
1     2
2     3
3     4
4     5
5     6
6     7
7     8
8     9
9    10
Name: column1, dtype: int64

In [0]:
df3.iloc[0:4,0:1]#start to end-1 values are extracted

column1
0        1
1        2
2        3
3        4

**Loc takes the labels where iloc takes the idexes**

---


In [0]:
#retrieving the information of DataFrame


In [0]:
df3.info()#Gives information regarding the dataframe being used

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   column1  10 non-null     int64  
 1   column2  10 non-null     float64
 2   column3  10 non-null     object 
dtypes: float64(1), int64(1), object(1)
memory usage: 368.0+ bytes


In [0]:
#Attributes

In [0]:
df3.shape

(10, 3)

In [0]:
df3.columns##gives all columns in the dataframe

Index(['column1', 'column2', 'column3'], dtype='object')

In [0]:
df3.index

RangeIndex(start=0, stop=10, step=1)

In [0]:
##Viewing data from DataFrame:
=head()
-tail()
-sample()

SyntaxError: ignored

In [0]:
df3.head()##if n is not mentioned half of the list is extracted

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c
3        4    45.56       d
4        5    56.67       e

In [0]:
df3.head(3)

column1  column2 column3
0        1    12.23       a
1        2    23.34       b
2        3    34.45       c

In [0]:
df3.tail()

column1  column2 column3
5        6    67.78       f
6        7    78.89       g
7        8    89.90       h
8        9    25.36       i
9       10    69.30       j

In [0]:
df3.tail(6)

column1  column2 column3
4        5    56.67       e
5        6    67.78       f
6        7    78.89       g
7        8    89.90       h
8        9    25.36       i
9       10    69.30       j

In [0]:
df3.sample()

column1  column2 column3
3        4    45.56       d

In [0]:
df3.sample()

column1  column2 column3
8        9    25.36       i

In [0]:
df3.sample(4)#sample is like random

column1  column2 column3
2        3    34.45       c
8        9    25.36       i
6        7    78.89       g
1        2    23.34       b

In [0]:
df3.describe()#column 3 didnt appear bcoz it donot have numbers as mean and min ... are calculated

column1   column2
count  10.00000  10.00000
mean    5.50000  50.34800
std     3.02765  26.17147
min     1.00000  12.23000
25%     3.25000  27.63250
50%     5.50000  51.11500
75%     7.75000  68.92000
max    10.00000  89.90000

In [0]:
#Changing the column names and indexes
df3 = df3.rename(columns={"column1":"First","column2":"Second","column3":"Third"})
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   34.45     c
3      4   45.56     d
4      5   56.67     e
5      6   67.78     f
6      7   78.89     g
7      8   89.90     h
8      9   25.36     i
9     10   69.30     j

In [0]:
df3.rename(columns={"column1":"First","column2":"Second","column3":"Third"},inplace = True)#inplace is to assign permanently,it can also be done by assigning to df3
df3

First  Second Third
0      1   12.23     a
1      2   23.34     b
2      3   34.45     c
3      4   45.56     d
4      5   56.67     e
5      6   67.78     f
6      7   78.89     g
7      8   89.90     h
8      9   25.36     i
9     10   69.30     j